name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: [ 'bug' ]
assignees:
  - "djenczewski"
body:
  - type: textarea
    id: Description
    attributes:
      label: Description
      placeholder: Briefly describe the issue.
    validations:
      required: true
  - type: textarea
    id: Steps-to-Reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Go to '...'

            2. Click on '...'

            3. Scroll to '...'
            
            4. Observe the error.
      "
    validations:
      required: true
  - type: textarea
    id: Expected-Behavior
    attributes:
      label: Expected Behavior
      placeholder: "Describe what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: Screenshots-or-Logs
    attributes:
      label: Screenshots or Logs
      placeholder: "If applicable, attach screenshots or relevant logs to help illustrate the issue."
  - type: textarea
    id: Additional-Context
    attributes:
      label: Additional Context
      placeholder: Add any other context about the problem here.
  - type: markdown
    id: Device-Details
    attributes:
      value: "## **Device Details**"
  - type: input
    id: Device
    attributes:
      label: Device
      placeholder: "MacBook Air"
  - type: input
    id: Os-Version
    attributes:
      label: Operating system and version
      placeholder: "Sequoia 15.1"
  - type: input
    id: cpu-arch
    attributes:
      label: CPU Architecture
      placeholder: "AArch64"
  - type: markdown
    id: Project-Details
    attributes:
      value: "## **Project Details**"
  - type: input
    id: privmx-endpoint-minimal-version
    attributes:
      label: PrivMX Endpoint Minimal version
      placeholder: ">=2.0 / 2.0.5"
    validations:
      required: true
  - type: input
    id: Language
    attributes:
      label: Language
      placeholder: "Java 21"
  - type: input
    id: Environment-Version
    attributes:
      label: Environment
      placeholder: "IntelliJ IDEA 2024.3"
  - type: markdown
    attributes:
      value: "## **Optionally**"
  - type: input
    attributes:
      label: "Link to the reproducible code repository."
  - type: textarea
    attributes:
      label: Include the specific code block causing the error in a code snippet
      render: java